// app/sveltekit/src/lib/components/Counter.svelte
<svelte:options immutable={true} />

<script lang="ts">
  import Button, { Label } from '@smui/button';
  import { createEventDispatcher } from 'svelte';

  // input props are declared using export let
  // if props are not given a value, they will be considered required
  export let label = 'Counter';
  export let count: number;

  // output events
  const dispatch = createEventDispatcher<{ increment: void; decrement: void }>();

  // reactive declaration
  $: doubleCount = count * 2;

  // variables are reactive, but they must be reassigned to update the DOM
  let timeSinceChange = 0;

  // reactive side effect, the dependency can just be in an empty statement if unused
  $: {
    count;
    resetTimeSinceChange();
  }

  // asynchronous state changes work as expected
  let interval = createTimer();
  function resetTimeSinceChange() {
    timeSinceChange = 0;
    clearInterval(interval);
    interval = createTimer();
  }

  function createTimer() {
    return window.setInterval(() => {
      timeSinceChange++;
    }, 1000);
  }

  function handleIncrement() {
    dispatch('increment');
  }
</script>

<div class="counter-wrapper">
  <h2>{label}</h2>
  <div class="counter-content">
    <h2>Count: {count}</h2>
    <h2>2x Count: {doubleCount}</h2>
    <h2>Time since change: {timeSinceChange}</h2>
    <Button variant="unelevated" on:click={handleIncrement}>
      <Label>Increment</Label>
    </Button>
  </div>
</div>

<style>
  .counter-wrapper {
    width: 400px;
    border: 1px black solid;
    border-radius: 10px;
    padding: 1rem;
  }

  .counter-content {
    display: flex;
    flex-direction: column;
    justify-content: center;
    align-items: center;
    gap: 1rem;
  }

  h2 {
    margin: 0;
  }
</style>

// app/vue-app/src/components/Counter.vue
<script setup lang="ts">
  interface Props {
    label?: string;
    count: number;
  }

  interface Emits {
    (e: 'increment'): void;
  }

  // define props assigns input props, and we can assign defaults using withDefaults
  const props = withDefaults(defineProps<Props>(), {
    label: 'Counter',
  });

  // the vue reactivity transform has a nicer way of doing this, but it is still experimental (although reportedly fairly stable now)
  // const { label = 'Counter', count } = defineProps<Props>();

  const timeSinceChange = ref(0);

  const emit = defineEmits<Emits>();

  const doubleCount = computed(() => props.count * 2);

  watch(
    () => props.count,
    () => resetTimeSinceChange()
  );

  let interval = createTimer();
  function resetTimeSinceChange() {
    timeSinceChange.value = 0;
    clearInterval(interval);
    interval = createTimer();
  }

  function createTimer() {
    return window.setInterval(() => {
      timeSinceChange.value++;
    }, 1000);
  }

  function handleIncrement() {
    emit('increment');
  }
</script>

<template>
  <div class="counter-wrapper">
    <h5>{{ label }}</h5>
    <div class="counter-content">
      <h5>Count: {{ count }}</h5>
      <h5>2x Count: {{ doubleCount }}</h5>
      <h5>Time since change: {{ timeSinceChange }}</h5>
      <q-btn color="primary" unelevated @click="handleIncrement()"
        >Increment</q-btn
      >
    </div>
  </div>
</template>

<style scoped>
  .counter-wrapper {
    width: 400px;
    border: 1px black solid;
    border-radius: 10px;
    padding: 1rem;
  }

  .counter-content {
    display: flex;
    flex-direction: column;
    justify-content: center;
    align-items: center;
    gap: 1rem;
  }

  h5 {
    margin: 0;
  }
</style>
