// app/sveltekit/src/lib/components/CounterParent.svelte
<script lang="ts">
  import Button, { Label } from '@smui/button';
  import Counter from '../../lib/components/Counter.svelte';

  let count = 0;

  function handleIncrement() {
    count++;
  }

  function handleReset() {
    count = 0;
  }
</script>

<div class="counter-container">
  <h2>Counter Parent</h2>
  <Counter {count} on:increment={handleIncrement} />
  <Button on:click={handleReset}><Label>Reset Counter</Label></Button>
</div>

<style>
  .counter-container {
    border: 1px black solid;
    padding: 1rem;
    border-radius: 10px;
    display: flex;
    flex-direction: column;
    gap: 1rem;
  }

  h2 {
    margin: 0;
  }
</style>

// app/react-app/src/components/CounterParent.tsx
import { Button, styled } from '@mui/material';
import { useState } from 'react';
import { Counter } from './Counter';

export const CounterParent = () => {
  const [count, setCount] = useState(0);

  function handleIncrement() {
    setCount((c) => c + 1);
  }

  function reset() {
    setCount(0);
  }

  return (
    <>
      <CounterWrapper>
        <CounterName>Counter Parent</CounterName>
        <Counter count={count} onIncrement={handleIncrement} />
        <Button onClick={reset}>Reset Counter</Button>
      </CounterWrapper>
    </>
  );
};

const CounterName = styled('h3')({
  margin: '0'
});

const CounterWrapper = styled('div')({
  border: '1px black solid',
  padding: '1rem',
  borderRadius: '10px',
  display: 'flex',
  flexDirection: 'column',
  gap: '1rem'
});
