// app/react-app/src/components/Counter.tsx
import { Button, ButtonGroup, Typography } from '@mui/material';
import { Box, Container, styled } from '@mui/system';
import { useEffect, useState } from 'react';

export const Counter = () => {
  const [count, setCount] = useState(0);
  const [doubleCount, setDoubleCount] = useState(0);
  const [countChanged, setCountChanged] = useState(0);

  useEffect(() => {
    setCountChanged(countChanged + 1);
  }, [count]);

  useEffect(() => {
    setDoubleCount(count * 2);
  }, [count]);

  return (
    <CounterWrapper>
      <Typography variant="h4">Counter</Typography>
      <CounterContent>
        <CounterValue count={count}>Count: {count}</CounterValue>
        <CounterValue>2x Count: {doubleCount}</CounterValue>
        <CounterValue>Times count changed: {countChanged}</CounterValue>
        <ButtonGroup disableElevation variant="contained">
          <Button disabled={count === 0} onClick={() => setCount(count - 1)}>
            -
          </Button>
          <Button onClick={() => setCount(count + 1)}>+</Button>
        </ButtonGroup>
      </CounterContent>
    </CounterWrapper>
  );
};

const CounterWrapper = styled(Box)(() => ({
  width: '400px',
  border: '1px black solid',
  borderRadius: '10px',
  padding: '1rem'
}));

const CounterContent = styled(Container)(() => ({
  display: 'flex',
  flexDirection: 'column',
  justifyContent: 'center',
  alignItems: 'center'
}));

const CounterValue = styled(Typography)((props: { count?: number }) => ({
  fontSize: '1.5rem'
  // fontSize: `${props.count ? 1 + 0.1 * props.count : 1.5}rem`
}));

// app/sveltekit/src/lib/components/Counter.svelte
<script lang="ts">
	import Button, { Label, Group } from '@smui/button';

	export let label = 'Counter';
	export let count = 0;

	$: doubleCount = count * 2;

	let countChanged = 0;
	$: count, countChanged++;
</script>

<div class="counter-wrapper">
	<h1>{label}</h1>
	<div class="counter-content">
		<h2>Count: {count}</h2>
		<h2>2x Count: {doubleCount}</h2>
		<h2>Count changed: {countChanged}</h2>
		<Group>
			<Button variant="unelevated" disabled={count === 0} on:click={() => count--}>
				<Label>-</Label>
			</Button>
			<Button variant="unelevated" on:click={() => count++}>
				<Label>+</Label>
			</Button>
		</Group>
	</div>
</div>

<style>
	.counter-wrapper {
		width: 400px;
		border: 1px black solid;
		border-radius: 10px;
		padding: 1rem;
	}

	.counter-content {
		display: flex;
		flex-direction: column;
		justify-content: center;
		align-items: center;
	}
</style>
