// app/vue-app/src/components/CounterParent.vue
<script setup lang="ts">
  import Counter from 'src/components/Counter.vue';

  const count = ref(0);

  function handleIncrement() {
    count.value++;
  }

  function handleReset() {
    count.value = 0;
  }
</script>

<template>
  <div class="counter-container rounded-borders">
    <h5 class="q-my-none">Counter Parent</h5>
    <Counter :count="count" @increment="handleIncrement"></Counter>
    <q-btn unelevated @click="handleReset">Reset Counter</q-btn>
  </div>
</template>

<style scoped>
  .counter-container {
    border: 1px black solid;
    padding: 1rem;
    border-radius: 10px;
    display: flex;
    flex-direction: column;
    gap: 1rem;
  }
</style>

// app/sveltekit/src/lib/components/CounterParent.svelte
<script lang="ts">
  import Button, { Label } from '@smui/button';
  import Counter from '../../lib/components/Counter.svelte';

  let count = 0;

  function handleIncrement() {
    count++;
  }

  function handleReset() {
    count = 0;
  }
</script>

<div class="counter-container">
  <h2>Counter Parent</h2>
  <Counter {count} on:increment={handleIncrement} />
  <Button on:click={handleReset}><Label>Reset Counter</Label></Button>
</div>

<style>
  .counter-container {
    border: 1px black solid;
    padding: 1rem;
    border-radius: 10px;
    display: flex;
    flex-direction: column;
    gap: 1rem;
  }

  h2 {
    margin: 0;
  }
</style>
